ui: mocha-bdd
browsers:
  - name: chrome
    version: 45..latest
  - name: firefox
    version: 40..latest
  - name: safari
    version: [7, 8, 9..latest]
  - name: ie
    version: 8..latest
  - name: microsoftedge
    version: 20..latest
  - name: iphone
    version: [7.0, 8.4, 9.1..latest]
  - name: ipad
    version: [7.0, 8.4, 9.1..latest]
  - name: android
    version: 4.0..latest
